import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { DotPattern } from "@/components/magicui/dot-pattern";
import { ModeToggle } from "@/components/ModeToggle";
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className="relative overflow-hidden">
        <div><Toaster /></div>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-4 right-4">
            <ModeToggle />
          </div>
          <DotPattern className="absolute inset-0 opacity-50"></DotPattern>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
