services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      BACKEND_API: http://backend:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://root:admin@mysql:3306/yunnet_db
      PORT: 4000
      JWT_SECRET: 8f1d2a9b3c4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0
    depends_on:
      - mysql
    command: sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 1; done && yarn db:dev && yarn start"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: yunnet_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: